# Generated by Django 5.1.2 on 2024-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Blog_Name', models.CharField(max_length=250)),
                ('Author_Name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
